env:
  browser: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
globals:
  $: false
  jQuery: false
  chrome: false
  network: true;